package GUI;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class OperationsPanel extends JPanel {

  /**
   * Creates new form OperationsPanel
   */
  public OperationsPanel() {
      initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

      updateGroup = new javax.swing.ButtonGroup();
      updateTitleLbl = new javax.swing.JLabel();
      flightNumLbl = new javax.swing.JLabel();
      flightNumTF = new javax.swing.JTextField();
      jButton1 = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      updateMsgFld = new javax.swing.JTextArea();
      updateMsgLbl = new javax.swing.JLabel();
      delayRB = new javax.swing.JRadioButton();
      cancellationRB = new javax.swing.JRadioButton();
      delayLbl = new javax.swing.JLabel();
      delayTimeTF = new javax.swing.JTextField();
      updateTypeLbl = new javax.swing.JLabel();

      updateTitleLbl.setText("Update Flight");

      flightNumLbl.setText("Flight Number:");

      flightNumTF.setText("Flight Number");

      jButton1.setText("Submit");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jButton1ActionPerformed(evt);
          }
      });

      updateMsgFld.setColumns(20);
      updateMsgFld.setRows(5);
      jScrollPane1.setViewportView(updateMsgFld);

      updateMsgLbl.setText("Update Message");

      updateGroup.add(delayRB);
      delayRB.setText("Delay");

      updateGroup.add(cancellationRB);
      cancellationRB.setText("Cancellation");

      delayLbl.setText("Delay Time:");

      delayTimeTF.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              delayTimeTFActionPerformed(evt);
          }
      });

      updateTypeLbl.setText("Update Type:");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
              .addContainerGap()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(layout.createSequentialGroup()
                                      .addComponent(updateMsgLbl)
                                      .addGap(394, 394, 394))
                                  .addGroup(layout.createSequentialGroup()
                                      .addComponent(jScrollPane1)
                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                              .addComponent(jButton1))
                          .addGroup(layout.createSequentialGroup()
                              .addComponent(updateTitleLbl)
                              .addGap(0, 0, Short.MAX_VALUE)))
                      .addContainerGap())
                  .addGroup(layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(flightNumLbl)
                          .addComponent(delayLbl))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                          .addComponent(flightNumTF, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                          .addComponent(delayTimeTF))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                      .addComponent(updateTypeLbl)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(cancellationRB)
                      .addGap(18, 18, 18)
                      .addComponent(delayRB)
                      .addGap(105, 105, 105))))
      );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addGap(35, 35, 35)
              .addComponent(updateTitleLbl)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(flightNumLbl)
                  .addComponent(flightNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(delayRB)
                  .addComponent(cancellationRB)
                  .addComponent(updateTypeLbl))
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(delayLbl)
                  .addComponent(delayTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGap(61, 61, 61)
              .addComponent(updateMsgLbl)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                      .addGap(18, 18, 18)
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                      .addGap(101, 101, 101)
                      .addComponent(jButton1)))
              .addContainerGap(313, Short.MAX_VALUE))
      );
  }// </editor-fold>                        

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
  }                                        

  private void delayTimeTFActionPerformed(java.awt.event.ActionEvent evt) {                                            
      // TODO add your handling code here:
  }                                           


  // Variables declaration - do not modify                     
  private javax.swing.JRadioButton cancellationRB;
  private javax.swing.JLabel delayLbl;
  private javax.swing.JRadioButton delayRB;
  private javax.swing.JTextField delayTimeTF;
  private javax.swing.JLabel flightNumLbl;
  private javax.swing.JTextField flightNumTF;
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.ButtonGroup updateGroup;
  private javax.swing.JTextArea updateMsgFld;
  private javax.swing.JLabel updateMsgLbl;
  private javax.swing.JLabel updateTitleLbl;
  private javax.swing.JLabel updateTypeLbl;
  // End of variables declaration                   
}